import { useState, useEffect } from "react";
import { Copy, Download, Sparkles, Check, RefreshCw } from "lucide-react";
import { Button } from "./ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface GeneratedPromptProps {
  formData: Record<string, any>;
}

export const GeneratedPrompt = ({ formData }: GeneratedPromptProps) => {
  const [prompt, setPrompt] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generatePrompt = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-website-prompt", {
        body: { formData },
      });

      if (error) throw error;

      if (data?.prompt) {
        setPrompt(data.prompt);
      }
    } catch (error) {
      console.error("Failed to generate prompt:", error);
      toast({
        title: "Couldn't generate prompt",
        description: "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    generatePrompt();
  }, []);

  const handleCopy = async () => {
    if (!prompt) return;
    
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      toast({
        title: "Copied to clipboard!",
        description: "You can now paste this prompt into your website builder.",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "Failed to copy",
        description: "Please select and copy manually.",
        variant: "destructive",
      });
    }
  };

  const handleDownload = () => {
    if (!prompt) return;
    
    const blob = new Blob([prompt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${formData.companyName || "website"}-website-prompt.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded!",
      description: "Check your downloads folder.",
    });
  };

  if (isLoading) {
    return (
      <div className="bg-card border border-border rounded-lg p-6 animate-pulse">
        <div className="flex items-center gap-3 mb-4">
          <div className="relative">
            <div className="absolute inset-0 bg-primary/30 rounded-full blur-md animate-pulse" />
            <Sparkles className="w-6 h-6 text-primary relative animate-spin" />
          </div>
          <div>
            <h2 className="font-heading text-xl font-bold text-foreground">Ava is generating your website prompt...</h2>
            <p className="text-sm text-muted-foreground">This may take a moment</p>
          </div>
        </div>
        <div className="space-y-3">
          <div className="h-4 bg-muted rounded w-full" />
          <div className="h-4 bg-muted rounded w-5/6" />
          <div className="h-4 bg-muted rounded w-4/6" />
          <div className="h-4 bg-muted rounded w-full" />
          <div className="h-4 bg-muted rounded w-3/4" />
        </div>
      </div>
    );
  }

  if (!prompt) {
    return (
      <div className="bg-card border border-border rounded-lg p-6 text-center">
        <p className="text-muted-foreground mb-4">Couldn't generate the prompt. Please try again.</p>
        <Button onClick={generatePrompt} variant="outline" className="gap-2">
          <RefreshCw className="w-4 h-4" />
          Retry
        </Button>
      </div>
    );
  }

  return (
    <div className="bg-card border border-primary/30 rounded-lg overflow-hidden shadow-lg shadow-primary/5">
      {/* Header */}
      <div className="bg-gradient-to-r from-primary/10 to-primary/5 border-b border-primary/20 px-6 py-4">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-3">
            <div className="relative">
              <div className="absolute inset-0 bg-primary/40 rounded-full blur-md" />
              <Sparkles className="w-6 h-6 text-primary relative" />
            </div>
            <div>
              <h2 className="font-heading text-xl font-bold text-foreground">Your Website Prompt</h2>
              <p className="text-sm text-muted-foreground">Generated by Ava based on your submission</p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <Button
              onClick={handleCopy}
              variant="outline"
              size="sm"
              className="gap-2"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button
              onClick={handleDownload}
              variant="outline"
              size="sm"
              className="gap-2"
            >
              <Download className="w-4 h-4" />
              Download
            </Button>
          </div>
        </div>
      </div>

      {/* Prompt Content */}
      <div className="p-6 max-h-[500px] overflow-y-auto">
        <pre className="text-sm text-foreground whitespace-pre-wrap font-mono bg-muted/30 rounded-lg p-4 border border-border">
          {prompt}
        </pre>
      </div>

      {/* Footer */}
      <div className="bg-muted/30 border-t border-border px-6 py-4">
        <p className="text-sm text-muted-foreground">
          💡 <strong>Tip:</strong> Copy this prompt and paste it into your preferred website builder to create your website automatically.
        </p>
      </div>
    </div>
  );
};

export default GeneratedPrompt;
